normalize_db_datetime_column <- function(values, column_name) {
  parsed_values <- as.POSIXct(
    as.character(values),
    format = "%Y-%m-%dT%H:%M:%SZ",
    tz = "UTC"
  )

  invalid_count <- sum(is.na(parsed_values))

  if (invalid_count > 0L) {
    fail(
      sprintf(
        "РќРµ СѓРґР°Р»РѕСЃСЊ РїРѕРґРіРѕС‚РѕРІРёС‚СЊ Рє Р·Р°РіСЂСѓР·РєРµ РєРѕР»РѕРЅРєСѓ %s: %s Р·РЅР°С‡РµРЅРёР№ РЅРµ РїСЂРёРІРµРґРµРЅС‹ Рє POSIXct.",
        column_name,
        invalid_count
      )
    )
  }

  parsed_values
}

prepare_articles_for_db <- function(articles_df) {
  required_columns <- article_required_columns()
  missing_columns <- setdiff(required_columns, names(articles_df))

  if (length(missing_columns) > 0L) {
    fail(
      sprintf(
        "РќРµРІРѕР·РјРѕР¶РЅРѕ РїРѕРґРіРѕС‚РѕРІРёС‚СЊ РґР°С‚Р°С„СЂРµР№Рј Рє Р·Р°РіСЂСѓР·РєРµ РІ PostgreSQL: РЅРµ С…РІР°С‚Р°РµС‚ РєРѕР»РѕРЅРѕРє %s.",
        paste(missing_columns, collapse = ", ")
      )
    )
  }

  if (nrow(articles_df) == 0L) {
    return(data.frame(
      news_id = numeric(),
      source = character(),
      title = character(),
      content_text = character(),
      published_at = as.POSIXct(character(), tz = "UTC"),
      url = character(),
      topic_tags = character(),
      extracted_at = as.POSIXct(character(), tz = "UTC"),
      stringsAsFactors = FALSE
    ))
  }

  news_id <- suppressWarnings(as.numeric(as.character(articles_df$news_id)))
  invalid_news_id_count <- sum(is.na(news_id))

  if (invalid_news_id_count > 0L) {
    fail(
      sprintf(
        "РќРµ СѓРґР°Р»РѕСЃСЊ РїРѕРґРіРѕС‚РѕРІРёС‚СЊ Рє Р·Р°РіСЂСѓР·РєРµ news_id: %s Р·РЅР°С‡РµРЅРёР№ РЅРµ С‡РёСЃР»РѕРІС‹Рµ.",
        invalid_news_id_count
      )
    )
  }

  data.frame(
    news_id = news_id,
    source = as.character(articles_df$source),
    title = as.character(articles_df$title),
    content_text = as.character(articles_df$content_text),
    published_at = normalize_db_datetime_column(articles_df$published_at, "published_at"),
    url = as.character(articles_df$url),
    topic_tags = as.character(articles_df$topic_tags),
    extracted_at = normalize_db_datetime_column(articles_df$extracted_at, "extracted_at"),
    stringsAsFactors = FALSE
  )
}

#' @title Connect to PostgreSQL
#' @description Opens a PostgreSQL connection using ETL database settings.
#' @param db_settings List with host, port, name, user, and password fields.
#' @param timeout_sec Connection timeout in seconds.
#' @return A DBI database connection.
#' @export
connect_postgres <- function(db_settings, timeout_sec = 60) {
  if (is.null(db_settings) || !is.list(db_settings)) {
    fail("РќРµ РїРµСЂРµРґР°РЅР° РєРѕРЅС„РёРіСѓСЂР°С†РёСЏ PostgreSQL.")
  }

  required_fields <- c("host", "port", "name", "user", "password")
  missing_fields <- required_fields[
    !vapply(required_fields, function(field_name) !is.null(db_settings[[field_name]]), logical(1))
  ]

  if (length(missing_fields) > 0L) {
    fail(
      sprintf(
        "РќРµРїРѕР»РЅР°СЏ РєРѕРЅС„РёРіСѓСЂР°С†РёСЏ PostgreSQL: %s.",
        paste(missing_fields, collapse = ", ")
      )
    )
  }

  DBI::dbConnect(
    drv = RPostgres::Postgres(),
    host = db_settings$host,
    port = as.integer(db_settings$port),
    dbname = db_settings$name,
    user = db_settings$user,
    password = db_settings$password,
    connect_timeout = as.integer(timeout_sec),
    bigint = "numeric",
    timezone = "UTC"
  )
}

#' @title Disconnect from PostgreSQL
#' @description Closes a PostgreSQL connection when it is valid.
#' @param conn DBI database connection or NULL.
#' @return Invisible logical value indicating whether a disconnect was attempted.
#' @export
disconnect_postgres <- function(conn) {
  if (is.null(conn)) {
    return(invisible(FALSE))
  }

  if (!DBI::dbIsValid(conn)) {
    return(invisible(FALSE))
  }

  DBI::dbDisconnect(conn)
  invisible(TRUE)
}

#' @title Create an ETL run record
#' @description Inserts a started ETL run into the etl_runs table.
#' @param conn DBI database connection.
#' @param started_at POSIXct-compatible start timestamp.
#' @param message Optional status message for the run.
#' @return Integer run identifier generated by the database.
#' @export
create_etl_run <- function(conn, started_at = Sys.time(), message = NULL) {
  started_at <- as.POSIXct(started_at, tz = "UTC")

  run_row <- DBI::dbGetQuery(
    conn,
    "
      INSERT INTO etl_runs (
        started_at,
        status,
        raw_count,
        normalized_count,
        inserted_count,
        duplicate_count,
        invalid_count,
        message
      )
      VALUES (
        $1, 'started', 0, 0, 0, 0, 0, $2
      )
      RETURNING run_id
    ",
    params = list(started_at, message)
  )

  as.integer(run_row$run_id[[1]])
}

#' @title Update an ETL run record
#' @description Updates final ETL run status, counters, timestamps, and message in the etl_runs table.
#' @param conn DBI database connection.
#' @param run_id ETL run identifier.
#' @param finished_at POSIXct-compatible finish timestamp.
#' @param status Final run status.
#' @param raw_count Number of raw records processed.
#' @param normalized_count Number of normalized records produced.
#' @param inserted_count Number of rows inserted into PostgreSQL.
#' @param duplicate_count Number of duplicate rows skipped.
#' @param invalid_count Number of invalid rows skipped.
#' @param message Optional final status message.
#' @return Invisible TRUE after the update executes.
#' @export
update_etl_run <- function(
  conn,
  run_id,
  finished_at = Sys.time(),
  status,
  raw_count = 0L,
  normalized_count = 0L,
  inserted_count = 0L,
  duplicate_count = 0L,
  invalid_count = 0L,
  message = NULL
) {
  finished_at <- as.POSIXct(finished_at, tz = "UTC")

  DBI::dbExecute(
    conn,
    "
      UPDATE etl_runs
      SET
        finished_at = $2,
        status = $3,
        raw_count = $4,
        normalized_count = $5,
        inserted_count = $6,
        duplicate_count = $7,
        invalid_count = $8,
        message = $9
      WHERE run_id = $1
    ",
    params = list(
      as.integer(run_id),
      finished_at,
      as.character(status),
      as.integer(raw_count),
      as.integer(normalized_count),
      as.integer(inserted_count),
      as.integer(duplicate_count),
      as.integer(invalid_count),
      message
    )
  )

  invisible(run_id)
}

split_dataframe_batches <- function(data, batch_size) {
  total_rows <- nrow(data)

  if (total_rows == 0L) {
    return(list())
  }

  batch_size <- as.integer(batch_size)
  if (is.na(batch_size) || batch_size <= 0L) {
    batch_size <- total_rows
  }

  batch_ids <- ceiling(seq_len(total_rows) / batch_size)
  split(data, batch_ids)
}

write_articles_stage_table <- function(conn, batch_df, stage_table = "etl_articles_stage") {
  DBI::dbWriteTable(
    conn,
    name = stage_table,
    value = batch_df,
    temporary = TRUE,
    overwrite = TRUE,
    row.names = FALSE
  )

  invisible(stage_table)
}

insert_articles_from_stage <- function(conn, stage_table = "etl_articles_stage") {
  inserted_rows <- DBI::dbGetQuery(
    conn,
    sprintf(
      "
        INSERT INTO articles (
          news_id,
          source,
          title,
          content_text,
          published_at,
          url,
          topic_tags,
          extracted_at
        )
        SELECT
          news_id,
          source,
          title,
          content_text,
          published_at,
          url,
          topic_tags,
          extracted_at
        FROM %s
        ON CONFLICT DO NOTHING
        RETURNING news_id
      ",
      stage_table
    )
  )

  as.integer(nrow(inserted_rows))
}

#' @title Load articles to PostgreSQL
#' @description Writes normalized article rows to a staging table and inserts non-duplicate rows into the target table.
#' @param conn DBI database connection.
#' @param articles_df Data frame of normalized articles.
#' @param batch_size Number of rows to write per batch.
#' @return List with total, inserted, and duplicate row counts.
#' @export
load_articles_to_db <- function(conn, articles_df, batch_size = 100L) {
  prepared_df <- prepare_articles_for_db(articles_df)
  total_rows <- nrow(prepared_df)

  if (total_rows == 0L) {
    return(list(
      total_rows = 0L,
      inserted_count = 0L,
      duplicate_count = 0L
    ))
  }

  inserted_count <- 0L
  stage_table <- "etl_articles_stage"
  batches <- split_dataframe_batches(prepared_df, batch_size = batch_size)

  DBI::dbWithTransaction(
    conn,
    {
      for (batch_df in batches) {
        write_articles_stage_table(conn, batch_df, stage_table = stage_table)
        inserted_count <- inserted_count + insert_articles_from_stage(conn, stage_table = stage_table)
      }

      DBI::dbExecute(conn, sprintf("DROP TABLE IF EXISTS %s", stage_table))
    }
  )

  duplicate_count <- as.integer(total_rows - inserted_count)

  list(
    total_rows = as.integer(total_rows),
    inserted_count = as.integer(inserted_count),
    duplicate_count = duplicate_count
  )
}
